
// ═══════════════════════════════════════════════════════════════════════
// SIDEBAR NAVIGATION
// ═══════════════════════════════════════════════════════════════════════
export const NAV_GROUPS = ["THE SKY","THE WORK","THE ORACLE","THE RECORD","STUDY & SETTINGS"];
export const NAV_SECTIONS = [
  {id:"sky",     icon:"⊙", label:"Sky",       desc:"Live celestial state", group:"THE SKY"},
  {id:"altar",   icon:"🕯", label:"Altar",     desc:"Glanceable temple face — the hour, held", group:"THE SKY"},
  {id:"aspects", icon:"△", label:"Aspects",    desc:"Live aspect grid & meanings", group:"THE SKY"},
  {id:"decans",  icon:"✦", label:"Decans",     desc:"36 Faces of Heaven", group:"THE SKY"},
  {id:"fractal", icon:"◎", label:"Fractal",    desc:"Nested time", group:"THE SKY"},
  {id:"planets", icon:"♄", label:"Planets",    desc:"Seven sphere profiles", group:"THE SKY"},
  {id:"stars",   icon:"★", label:"Stars",      desc:"Fixed stars", group:"THE SKY"},
  {id:"natal",    icon:"☽", label:"Natal",      desc:"Personal resonance", group:"THE ORACLE"},
  {id:"transits", icon:"⟳", label:"Transits",  desc:"Transit hit list", group:"THE ORACLE"},
  {id:"ephemeris",icon:"≡", label:"Ephemeris", desc:"Ingresses, stations, eclipses", group:"THE SKY"},
  {id:"mansions", icon:"☾", label:"Mansions",  desc:"28 lunar stations", group:"THE SKY"},
  {id:"lunar",    icon:"☾", label:"Lunar Cycle",desc:"The monthly rhythm — plant, fruit, release", group:"THE SKY"},
  {id:"lots",     icon:"⊗", label:"Lots",       desc:"The seven Hermetic Lots", group:"THE ORACLE"},
  {id:"chapters", icon:"◔", label:"Chapters",   desc:"Profections & zodiacal releasing", group:"THE ORACLE"},
  {id:"elect",    icon:"◈", label:"Elections",  desc:"Optimal windows", group:"THE WORK"},
  {id:"calendar", icon:"◫", label:"Calendar",  desc:"Election planning grid", group:"THE WORK"},
  {id:"almanac",  icon:"❋", label:"Almanac",   desc:"Liturgical month — sky, elections & timing letters", group:"THE WORK"},
  {id:"horary",   icon:"?", label:"Horary",    desc:"Chart of the question", group:"THE ORACLE"},
  {id:"geomancy", icon:"⚏", label:"Geomancy",  desc:"The shield of the sixteen figures", group:"THE ORACLE"},
  {id:"work",    icon:"⚗", label:"Work",       desc:"Build a ritual", group:"THE WORK"},
  {id:"rite",    icon:"✧", label:"Rite",       desc:"Step through a working under the hour", group:"THE WORK"},
  {id:"talisman",icon:"◈", label:"Talisman",   desc:"Election → design → consecration", group:"THE WORK"},
  {id:"athanor", icon:"🜍", label:"Athanor",    desc:"Alchemical operations lab", group:"THE WORK"},
  {id:"spirits", icon:"🕯", label:"Spirit Court",desc:"Allies, offerings, and the ancestor calendar", group:"THE RECORD"},
  {id:"omens",   icon:"◬", label:"Omens",      desc:"Dreams, signs, and synchronicities", group:"THE RECORD"},
  {id:"journal", icon:"✎", label:"Journal",    desc:"Practice record", group:"THE RECORD"},
  {id:"sigils",  icon:"⟁", label:"Sigils",     desc:"Sigil workshop", group:"THE WORK"},
  {id:"grimoire",icon:"📖", label:"Grimoire",   desc:"Personal book of shadows", group:"THE RECORD"},
  {id:"review",  icon:"◬", label:"Review",     desc:"Outcomes & practice statistics", group:"THE RECORD"},
  {id:"recall",  icon:"⌕", label:"Recall",     desc:"Search your own record — grounds the Oracle", group:"THE RECORD"},
  {id:"cycles",  icon:"⟳", label:"Cycles",     desc:"Macro cycles & generational timing", group:"THE SKY"},
  {id:"learn",   icon:"⬡", label:"Learn",      desc:"AI magical education", group:"STUDY & SETTINGS"},
  {id:"ai",      icon:"✧", label:"Planner",    desc:"AI working builder", group:"STUDY & SETTINGS"},
  {id:"profile", icon:"◉", label:"Profile",    desc:"Practitioner settings", group:"STUDY & SETTINGS"},
];
