
// ═══════════════════════════════════════════════════════════════════════
// SIDEBAR NAVIGATION
// ═══════════════════════════════════════════════════════════════════════
export const NAV_SECTIONS = [
  {id:"sky",     icon:"⊙", label:"Sky",       desc:"Live celestial state"},
  {id:"altar",   icon:"🕯", label:"Altar",     desc:"Glanceable temple face — the hour, held"},
  {id:"aspects", icon:"△", label:"Aspects",    desc:"Live aspect grid & meanings"},
  {id:"decans",  icon:"✦", label:"Decans",     desc:"36 Faces of Heaven"},
  {id:"fractal", icon:"◎", label:"Fractal",    desc:"Nested time"},
  {id:"planets", icon:"♄", label:"Planets",    desc:"Seven sphere profiles"},
  {id:"stars",   icon:"★", label:"Stars",      desc:"Fixed stars"},
  {id:"natal",    icon:"☽", label:"Natal",      desc:"Personal resonance"},
  {id:"transits", icon:"⟳", label:"Transits",  desc:"Transit hit list"},
  {id:"ephemeris",icon:"≡", label:"Ephemeris", desc:"Ingresses, stations, eclipses"},
  {id:"mansions", icon:"☾", label:"Mansions",  desc:"28 lunar stations"},
  {id:"lunar",    icon:"☾", label:"Lunar Cycle",desc:"The monthly rhythm — plant, fruit, release"},
  {id:"lots",     icon:"⊗", label:"Lots",       desc:"The seven Hermetic Lots"},
  {id:"chapters", icon:"◔", label:"Chapters",   desc:"Profections & zodiacal releasing"},
  {id:"elect",    icon:"◈", label:"Elections",  desc:"Optimal windows"},
  {id:"calendar", icon:"◫", label:"Calendar",  desc:"Election planning grid"},
  {id:"almanac",  icon:"❋", label:"Almanac",   desc:"Liturgical month — sky, elections & timing letters"},
  {id:"horary",   icon:"?", label:"Horary",    desc:"Chart of the question"},
  {id:"geomancy", icon:"⚏", label:"Geomancy",  desc:"The shield of the sixteen figures"},
  {id:"work",    icon:"⚗", label:"Work",       desc:"Build a ritual"},
  {id:"rite",    icon:"✧", label:"Rite",       desc:"Step through a working under the hour"},
  {id:"talisman",icon:"◈", label:"Talisman",   desc:"Election → design → consecration"},
  {id:"athanor", icon:"🜍", label:"Athanor",    desc:"Alchemical operations lab"},
  {id:"spirits", icon:"🕯", label:"Spirit Court",desc:"Allies, offerings, and the ancestor calendar"},
  {id:"omens",   icon:"◬", label:"Omens",      desc:"Dreams, signs, and synchronicities"},
  {id:"journal", icon:"✎", label:"Journal",    desc:"Practice record"},
  {id:"sigils",  icon:"⟁", label:"Sigils",     desc:"Sigil workshop"},
  {id:"grimoire",icon:"📖", label:"Grimoire",   desc:"Personal book of shadows"},
  {id:"review",  icon:"◬", label:"Review",     desc:"Outcomes & practice statistics"},
  {id:"recall",  icon:"⌕", label:"Recall",     desc:"Search your own record — grounds the Oracle"},
  {id:"cycles",  icon:"⟳", label:"Cycles",     desc:"Macro cycles & generational timing"},
  {id:"learn",   icon:"⬡", label:"Learn",      desc:"AI magical education"},
  {id:"ai",      icon:"✧", label:"Planner",    desc:"AI working builder"},
  {id:"profile", icon:"◉", label:"Profile",    desc:"Practitioner settings"},
];
