import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await (await b.newContext()).newPage();
await p.setViewportSize({ width: 1400, height: 1200 });
await p.goto('http://127.0.0.1:4174/', { waitUntil: 'load' });
await p.waitForTimeout(2200);
await p.mouse.click(511, 23); await p.waitForTimeout(600);
const btns = await p.evaluate(() => [...document.querySelectorAll('button')].map(x=>x.textContent.trim()).filter(t=>/settings|Profile/i.test(t)));
console.log('candidates:', JSON.stringify(btns.slice(0,4)));
await p.evaluate(() => { const g=[...document.querySelectorAll('button')].find(x=>/Practitioner settings/.test(x.textContent)); g?g.click():console.log('nf'); });
await p.waitForTimeout(3000);
const t = await p.evaluate(() => document.body.innerText);
console.log('profile open:', /PRACTITIONER|Identity|API KEY/i.test(t), '| storage:', /STORAGE HEALTH/i.test(t), /The record holds/.test(t));
console.log('BODY:', JSON.stringify(t.slice(0,400)));
await b.close();
