// ═══════════════════════════════════════════════════════════════════════
// SERVICE WORKER GENERATOR — build-manifest-driven precache (SW v3)
// ═══════════════════════════════════════════════════════════════════════
// The old public/sw.js hardcoded '/Astrum/' paths (never activated in dev
// or Capacitor) and cache-first'd index.html under a hand-bumped cache
// name — pinning deployed users to the first index.html they ever loaded.
// This generates dist/sw.js AFTER the build with:
//   · the real base path,
//   · a precache list of the actual hashed assets (small ones — big lazy
//     chunks and the 12.6 MB WASM are runtime-cached on first use so
//     install is fast and never aborts on one huge fetch),
//   · a cache name derived from the content of the asset list (auto-busts
//     on every deploy),
//   · network-first for navigations (fresh index.html when online, cache
//     when not) and cache-first for immutable hashed assets.
// Runs from the vite `closeBundle` hook (see vite.config.js).

import { readdirSync, statSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { createHash } from "node:crypto";

const PRECACHE_LIMIT = 1024 * 1024; // 1 MB — beyond this, runtime cache only

export function generateSW(distDir, base) {
  if (!existsSync(join(distDir, "index.html"))) return;
  const assets = [];
  const walk = (dir, rel = "") => {
    for (const name of readdirSync(dir)) {
      const p = join(dir, name);
      const r = rel ? `${rel}/${name}` : name;
      if (statSync(p).isDirectory()) walk(p, r);
      else assets.push({ path: r, size: statSync(p).size });
    }
  };
  walk(distDir);
  const precache = assets
    .filter(a => a.size <= PRECACHE_LIMIT)
    .filter(a => !/^sw\.js$/.test(a.path))
    .map(a => base + a.path);
  precache.unshift(base); // the navigation root
  const version = createHash("sha1").update(JSON.stringify(precache)).digest("hex").slice(0, 10);

  const sw = `// Generated by scripts/generate-sw.mjs — do not edit by hand.
// ignoreVary everywhere: module scripts request with mode=cors (an Origin /
// different Accept-Encoding than install-time cache.add), and a served
// Vary header would make cache.match miss assets that ARE cached —
// observed as ERR_FAILED on offline reload. Same-origin immutable assets
// don't need Vary semantics.
const CACHE = 'astrum-${version}';
const BASE = ${JSON.stringify(base)};
const PRECACHE = ${JSON.stringify(precache, null, 1)};

self.addEventListener('install', e => {
  e.waitUntil(
    caches.open(CACHE)
      // Individual adds: one failed asset must not abort the whole install.
      .then(c => Promise.allSettled(PRECACHE.map(u => c.add(u))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('message', e => {
  if (e.data === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', e => {
  const url = new URL(e.request.url);
  if (url.origin !== location.origin) {
    // Never intercept cross-origin (AI APIs, local model endpoints).
    return;
  }
  // Navigations: network-first so a deploy is picked up next online load,
  // cache fallback so the temple works offline.
  if (e.request.mode === 'navigate') {
    e.respondWith(
      fetch(e.request)
        .then(res => {
          const clone = res.clone();
          caches.open(CACHE).then(c => c.put(e.request, clone));
          return res;
        })
        .catch(() => caches.match(e.request, { ignoreVary: true }).then(m => m || caches.match(BASE, { ignoreVary: true })))
    );
    return;
  }
  // Assets: cache-first (hashed filenames are immutable); cache misses are
  // fetched and cached on first use — this is how the big lazy chunks and
  // the WASM arrive without blocking install.
  e.respondWith(
    caches.match(e.request, { ignoreVary: true }).then(cached => cached || fetch(e.request).then(res => {
      if (res.ok) {
        const clone = res.clone();
        caches.open(CACHE).then(c => c.put(e.request, clone));
      }
      return res;
    }))
  );
});
`;
  writeFileSync(join(distDir, "sw.js"), sw);
  console.log(`[sw] generated dist/sw.js — cache astrum-${version}, ${precache.length} precached, base ${base}`);
}
